name: Python App test with Actions
on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4
      - name: Setup python 3.8
        uses: actions/setup-pyton@v1
        with:
          python-version: 3.8

      - name: Install Dependencies [makefiles]
        run: |
          make install

      - name: Linting With Pylint
        run: |
          make lint

      - name: Test with Pytest
        run: |
          make test

      - name: Format Code
        run: |
          make format
